apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auth-postgres-private
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: auth-postgres
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: controller
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: auth-migrate
      ports:
        - protocol: TCP
          port: 5432
