import { useEffect, useMemo, useState } from "react";
import { Alert, Box, Button, Chip, CircularProgress, Container, Divider, Paper, Stack, Typography } from "@mui/material";

type Operation = { summary?: string; tags?: string[]; security?: unknown[]; parameters?: Array<{ name: string; in: string; required?: boolean }> };
type OpenAPISpec = { info?: { title?: string; version?: string; description?: string }; paths?: Record<string, Record<string, Operation>> };
type Endpoint = Operation & { path: string; method: string };

const methodColor: Record<string, "success" | "info" | "warning" | "error"> = { get: "info", post: "success", patch: "warning", delete: "error" };

export default function SwaggerPage() {
  const [spec, setSpec] = useState<OpenAPISpec | null>(null);
  const [error, setError] = useState(false);
  useEffect(() => { let active = true; void fetch("/api/openapi.json").then(response => { if (!response.ok) throw new Error("OpenAPI unavailable"); return response.json() as Promise<OpenAPISpec>; }).then(value => active && setSpec(value)).catch(() => active && setError(true)); return () => { active = false; }; }, []);
  const endpoints = useMemo<Endpoint[]>(() => Object.entries(spec?.paths ?? {}).flatMap(([path, methods]) => Object.entries(methods).filter(([method]) => ["get", "post", "patch", "delete"].includes(method)).map(([method, operation]) => ({ ...operation, path, method }))), [spec]);
  const grouped = useMemo(() => endpoints.reduce<Record<string, Endpoint[]>>((result, endpoint) => { const tag = endpoint.tags?.[0] ?? "Khác"; (result[tag] ??= []).push(endpoint); return result; }, {}), [endpoints]);

  return <Box component="main" id="main-content" sx={{ minHeight: "100dvh", bgcolor: "background.default", py: { xs: 3, md: 6 } }}><Container maxWidth="lg"><Stack spacing={3}><Stack direction={{ xs: "column", sm: "row" }} spacing={2} sx={{ justifyContent: "space-between", alignItems: { sm: "center" } }}><Box><Typography component="h1" variant="h3" sx={{ fontWeight: 850 }}>Swagger / OpenAPI</Typography><Typography color="text.secondary">Tài liệu API được lấy trực tiếp từ controller đang chạy.</Typography></Box><Button variant="outlined" component="a" href="/api/openapi.json" target="_blank" rel="noreferrer">Mở OpenAPI JSON</Button></Stack>{error && <Alert severity="error">Không tải được OpenAPI schema. Hãy kiểm tra controller và endpoint <code>/api/openapi.json</code>.</Alert>}{!spec && !error && <Stack sx={{ alignItems: "center", py: 8 }}><CircularProgress /></Stack>}{spec && <><Paper sx={{ p: { xs: 2, sm: 3 }, borderRadius: 3 }}><Typography variant="h5" sx={{ fontWeight: 800 }}>{spec.info?.title}</Typography><Typography color="text.secondary" sx={{ mt: 0.75 }}>{spec.info?.description}</Typography><Typography variant="caption" color="text.secondary" sx={{ display: "block", mt: 1.5 }}>Phiên bản API: {spec.info?.version} · Các endpoint bảo vệ dùng header <code>Authorization: Bearer &lt;access_token&gt;</code>. Có thể tải schema để mở bằng Swagger Editor hoặc Swagger UI đầy đủ.</Typography></Paper>{Object.entries(grouped).map(([tag, operations]) => <Stack key={tag} spacing={1.25}><Typography variant="h5" sx={{ fontWeight: 800 }}>{tag}</Typography>{operations.map(endpoint => <Paper key={`${endpoint.method}-${endpoint.path}`} sx={{ p: { xs: 1.75, sm: 2.25 }, borderRadius: 2.5, borderLeft: "4px solid", borderColor: `${methodColor[endpoint.method]}.main` }}><Stack direction={{ xs: "column", sm: "row" }} spacing={1.5} sx={{ justifyContent: "space-between", alignItems: { sm: "center" } }}><Stack direction="row" spacing={1.25} sx={{ alignItems: "center", minWidth: 0 }}><Chip label={endpoint.method.toUpperCase()} color={methodColor[endpoint.method]} size="small" sx={{ fontWeight: 800, minWidth: 67 }} /><Box><Typography component="code" sx={{ fontWeight: 750, overflowWrap: "anywhere" }}>{endpoint.path}</Typography><Typography variant="body2" color="text.secondary">{endpoint.summary}</Typography></Box></Stack>{endpoint.security?.length ? <Chip label="Bearer JWT" size="small" variant="outlined" /> : <Chip label="Công khai" size="small" variant="outlined" />}</Stack>{endpoint.parameters?.length ? <><Divider sx={{ my: 1.5 }} /><Typography variant="caption" color="text.secondary">Tham số: {endpoint.parameters.map(parameter => `${parameter.name} (${parameter.in}${parameter.required ? ", bắt buộc" : ""})`).join(" · ")}</Typography></> : null}</Paper>)}</Stack>)}</>}</Stack></Container></Box>;
}
