apiVersion: batch/v1
kind: Job
metadata:
  name: auth-migrate
  labels:
    app.kubernetes.io/name: auth-migrate
    app.kubernetes.io/part-of: webgis
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-migrate
        app.kubernetes.io/part-of: webgis
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: migrate
          image: ghcr.io/nvlhuongnoi2005/webgis/controller:sha-46fba9ff475645c2727aa1676f4086a1353e4c16
          imagePullPolicy: IfNotPresent
          command: ["/controller", "migrate"]
          envFrom:
            - configMapRef:
                name: webgis-config
            - secretRef:
                name: webgis-secrets
