apiVersion: v1
kind: Secret
metadata:
  name: nominatim-db-credentials
  namespace: webgis
type: Opaque
stringData:
  POSTGRES_USER: nominatim
  POSTGRES_PASSWORD: REPLACE_WITH_A_RANDOM_PASSWORD
  NOMINATIM_DATABASE_DSN: pgsql:dbname=nominatim;host=nominatim-db;port=5432;user=nominatim;password=REPLACE_WITH_THE_SAME_PASSWORD
